# Generated by Django 6.0.1 on 2026-01-09 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticeID', models.IntegerField(max_length=1000)),
                ('noticeTitle', models.CharField(max_length=256)),
                ('noticeDescription', models.TextField()),
                ('noticeCreate', models.DateTimeField(auto_now_add=True)),
                ('noticeImage', models.ImageField(upload_to='noticePhoto')),
                ('noticeCatagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice.catagory')),
            ],
        ),
    ]
