# Generated by Django 6.0.1 on 2026-01-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('teacher', 'Teacher'), ('staff', 'Staff'), ('admin', 'Admin')], max_length=20)),
                ('memberName', models.CharField(max_length=200)),
                ('memberDesignation', models.CharField(max_length=200)),
                ('memberDepartment', models.CharField(max_length=200)),
                ('memberEmail', models.EmailField(max_length=254, unique=True)),
                ('memberPhone', models.CharField(max_length=11)),
                ('memberImage', models.ImageField(blank=True, null=True, upload_to='schoolmember/images/')),
                ('memberApprove', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
